add_newline = false

format = """$directory$character"""

palette = "gruvbox"

right_format = """$all"""

[character]
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
style = "purple"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'green'
deleted_style = 'red'
ignore_submodules = true
disabled = false

[git_status]
style = "cyan"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style)) "
conflicted = "[◪◦](italic red)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic brown)"
untracked = "[◌◦](italic dimmed yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦]( dimmed orange)"
staged = "[▪┤[$count](bold white)│](italic cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

[golang]
format = '[󰟓 ](cyan)'

[nodejs]
format = '[](green)'

[bun]
format = '[](white)'

[directory]
truncation_length = 4
style = "white"

[cmd_duration]
format = ' took [$duration]($style)'
style = "orange"

[palettes.gruvbox]
base00 = "#32302f" # ----
base01 = "#3c3836" # ---
base02 = "#504945" # --
base03 = "#665c54" # -
base04 = "#bdae93" # +
base05 = "#d5c4a1" # ++
base06 = "#ebdbb2" # +++
base07 = "#fbf1c7" # ++++
red = "#fb4934" # red
orange = "#fe8019" # orange
yellow = "#fabd2f" # yellow
green = "#b8bb26" # green
cyan = "#8ec07c" # aqua/cyan
blue = "#83a598" # blue
purple = "#d3869b" # purple
brown = "#d65d0e" # brown

# [palettes.eink]
# background= "#CCCCCC"
# foreground= "#474747"
# cursor= "#333333"
# color0= "#CCCCCC"
# color1= "#474747"
# color2= "#666666"
# color3= "#999999"
# color4= "#333333"
# color5= "#808080"
# color6= "#AAAAAA"
# color7= "#555555"
# color8= "#222222"
# color9= "#B3B3B3"
# color10= "#3D3D3D"
# color11= "#E0E0E0"
# color12= "#1A1A1A"
# color13= "#999999"
# color14= "#666666"
# color15= "#F5F5F5"
